module:
  imports:
    - path: github.com/marcpabst/hugo-maps


params:
  hugo-maps:
      default:
        tileJSON: hhttps://api.maptiler.com/tiles/v3/tiles.json?key=v5K1SmwDQ21QRKA2KOug
      my_map:
        center: [35.85194537795955, 127.1286255985083]
        zoom: 2