module:
  imports:
    - path: github.com/marcpabst/hugo-maps
params:
  hugo-maps:
    default:
      tileJSON: https://api.maptiler.com/maps/aquarelle/?key=v5K1SmwDQ21QRKA2KOug#1.0/0.00000/0.00000
    my_map:
      center: [35.85, 127.12]
      zoom: 2
